#
# Copyright (C) 2024 Intel Corporation.
#
# SPDX-License-Identifier: Apache-2.0
#


 ## Current Developer Toolbox doesn't support environment files, make sure to remove any files or environment variables starting with $
version: '3.7'
services:
  camera-simulator:
    container_name: camera-simulator
    image: aler9/rtsp-simple-server
    ports:
      - "127.0.0.1:8554:8554"
  camera-simulator0:
    build:
      context: .
    image: openvino/ubuntu20_data_runtime:2021.4.2
    container_name: camera-simulator0
    network_mode: "host"
    entrypoint: ffmpeg
    command: "
        -nostdin
        -re -stream_loop -1
        -i /home/pipeline-server/sample-media/coca-cola-4465029-1920-15-bench.mp4
        -c copy
        -f rtsp
        -rtsp_transport
        tcp
        rtsp://localhost:8554/camera_0
        "
    depends_on:
      - camera-simulator
    volumes:
      - ./sample-media:/home/pipeline-server/sample-media
  camera-simulator1:
    build:
      context: .
    image: openvino/ubuntu20_data_runtime:2021.4.2
    container_name: camera-simulator1
    network_mode: "host"
    entrypoint: ffmpeg
    command: "
        -nostdin
        -re -stream_loop -1
        -i /home/pipeline-server/sample-media/vehicle-bike-1920-15-bench.mp4
        -c copy
        -f rtsp
        -rtsp_transport
        tcp
        rtsp://localhost:8554/camera_1
        "
    depends_on:
      - camera-simulator
    volumes:
      - ./sample-media:/home/pipeline-server/sample-media
  camera-simulator2:
    build:
      context: .
    image: openvino/ubuntu20_data_runtime:2021.4.2
    container_name: camera-simulator2
    network_mode: "host"
    entrypoint: ffmpeg
    command: "
        -nostdin
        -re -stream_loop -1
        -i /home/pipeline-server/sample-media/video_of_people_walking_855564-1920-15-bench.mp4
        -c copy
        -f rtsp
        -rtsp_transport
        tcp
        rtsp://localhost:8554/camera_2
        "
    depends_on:
      - camera-simulator
    volumes:
      - ./sample-media:/home/pipeline-server/sample-media

  OvmsClient_capi_yolov5:
    image: openvino/model_server-capi-gst-ovms-capi_yolov5:latest
    deploy:
      mode: replicated
      replicas: 2
    network_mode: "host"
    user: root
    privileged: true
    entrypoint: /opencv-ovms/scripts/docker_compose_generic_entrypoint.sh
    env_file:
      - ./configs/opencv-ovms/envs/capi_yolov5.env
    environment:
      - CONTAINER_NAME="capi_yolov50"
      - INPUTSRC=rtsp://localhost:8554/camera_1
      - RENDER_MODE=0 #RENDER_MODE=1 will work only after running xhost +local:docker
      - DISPLAY=$DISPLAY
      - PLATFORM=CPU
      - BARCODE=0
      - OVMS_MODEL_CONFIG_JSON=/models/config.json
      - PIPELINE_PROFILE=capi_yolov5
      - ENTRYPOINT_SCRIPT=/opencv-ovms/gst_capi/run_gst_capi.sh
    volumes:
      - ./configs/opencv-ovms:/opencv-ovms
      - ./results:/tmp/results
      - ~/.Xauthority:/home/dlstreamer/.Xauthority
      - /tmp/.X11-unix
      - ~/.cl-cache:/home/intel/gst-ovms/.cl-cache
      - ./sample-media/:/home/intel/gst-ovms/vids
      - ./configs/opencv-ovms/gst_capi/extensions:/home/intel/gst-ovms/extensions
      - ./configs/opencv-ovms/models/2022:/models

  OvmsClient_capi_yolov5_ensemble:
    image: openvino/model_server-capi-gst-ovms-capi_yolov5_ensemble:latest
    deploy:
      mode: replicated
      replicas: 2
    network_mode: "host"
    user: root
    privileged: true
    entrypoint: /opencv-ovms/scripts/docker_compose_generic_entrypoint.sh
    env_file:
      - ./configs/opencv-ovms/envs/capi_yolov5_ensemble.env
    environment:
      - CONTAINER_NAME="capi_yolov5_ensemble0"
      - INPUTSRC=rtsp://localhost:8554/camera_0
      - RENDER_MODE=0 #RENDER_MODE=1 will work only after running xhost +local:docker
      - DISPLAY=$DISPLAY
      - PLATFORM=CPU
      - BARCODE=0
      - OVMS_MODEL_CONFIG_JSON=/models/config.json
      - PIPELINE_PROFILE=capi_yolov5_ensemble
      - ENTRYPOINT_SCRIPT=/opencv-ovms/gst_capi/run_gst_capi.sh
    volumes:
      - ./configs/opencv-ovms:/opencv-ovms
      - ./results:/tmp/results
      - ~/.Xauthority:/home/dlstreamer/.Xauthority
      - /tmp/.X11-unix
      - ~/.cl-cache:/home/intel/gst-ovms/.cl-cache
      - ./sample-media/:/home/intel/gst-ovms/vids
      - ./configs/opencv-ovms/gst_capi/extensions:/home/intel/gst-ovms/extensions
      - ./configs/opencv-ovms/models/2022:/models

  OvmsClient_capi_face_detection:
    image: openvino/model_server-capi-gst-ovms-face_detection:latest
    deploy:
      mode: replicated
      replicas: 2
    network_mode: "host"
    user: root
    privileged: true
    entrypoint: /opencv-ovms/scripts/docker_compose_generic_entrypoint.sh
    env_file:
      - ./configs/opencv-ovms/envs/capi_face_detection.env
    environment:
      - CONTAINER_NAME="capi_face_detection0"
      - INPUTSRC=rtsp://localhost:8554/camera_2
      - RENDER_MODE=0 #RENDER_MODE=1 will work only after running xhost +local:docker
      - DISPLAY=$DISPLAY
      - PLATFORM=CPU
      - BARCODE=0
      - OVMS_MODEL_CONFIG_JSON=/models/config.json
      - PIPELINE_PROFILE=capi_face_detection
      - ENTRYPOINT_SCRIPT=/opencv-ovms/gst_capi/run_gst_capi.sh
    volumes:
      - ./configs/opencv-ovms:/opencv-ovms
      - ./results:/tmp/results
      - ~/.Xauthority:/home/dlstreamer/.Xauthority
      - /tmp/.X11-unix
      - ~/.cl-cache:/home/intel/gst-ovms/.cl-cache
      - ./sample-media/:/home/intel/gst-ovms/vids
      - ./configs/opencv-ovms/gst_capi/extensions:/home/intel/gst-ovms/extensions
      - ./configs/opencv-ovms/models/2022:/models
