#
# Copyright (C) 2023 Intel Corporation.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3.7'
volumes:
  portainer_data:
  
services:
  portainer:
    image:  portainer/portainer-ce
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:z
      - portainer_data:/data
    restart: always