#
# Copyright (C) 2023 Intel Corporation.
#
# SPDX-License-Identifier: BSD-3-Clause
#

FROM openvino/ubuntu22_dev:latest

USER root 

RUN apt-get update -y || true; DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    wget && \
    rm -rf /var/lib/apt/lists/*

COPY download_models/download_mo_bit_models.sh /
RUN chmod +x /download_mo_bit_models.sh

RUN mkdir -p /result

WORKDIR /

ENTRYPOINT [ "/download_mo_bit_models.sh" ]
