version: '3.8'

services:
  model-downloader:
    image: iotgdevcloud/modeldownloader:latest
    container_name: model-downloader
    environment:
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - MODELS_DIR=/workspace/models
    volumes:
      - ./models:/workspace/models
    restart: "no"
    profiles:
      - download-needed

  camera-simulator-reg:
    container_name: camera-simulator-reg
    image: bluenviron/mediamtx
    ports:
      - "127.0.0.1:8554:8554"

  camera-streamer0-reg:
    image: jrottenberg/ffmpeg:4.1-alpine
    container_name: camera-streamer0-reg
    network_mode: "host"
    environment:
      - PIPELINE_SCRIPT=${PIPELINE_SCRIPT:-yolo11n.sh}
    entrypoint: ["/bin/sh", "/home/pipeline-server/src/start_stream.sh"]
    depends_on:
      camera-simulator-reg:
        condition: service_started
    volumes:
      - ./performance-tools/sample-media:/home/pipeline-server/sample-media
      - ./src/start_stream.sh:/home/pipeline-server/src/start_stream.sh
      - ./src:/home/pipeline-server/src

  dlstreamer-app:
    image: iotgdevcloud/dlstreamer:latest
    container_name: dlstreamer-app
    depends_on:
      camera-streamer0-reg:
        condition: service_started
      camera-simulator-reg:
        condition: service_started
    network_mode: "host"
    entrypoint: /home/pipeline-server/src/entrypoint.sh --pipeline_script_choice ${PIPELINE_SCRIPT:-yolo11n.sh}
    privileged: true
    ipc: "host"
    env_file:
      - .env.registry
      - ./src/res/all-cpu.env
    environment:
      - DISPLAY=${DISPLAY}
      - CONTAINER_NAME=${CONTAINER_NAME}
      - INPUTSRC=${INPUTSRC}
      - INPUTSRC_AP1=${INPUTSRC_AP1}
      - INPUTSRC_OC1=${INPUTSRC_OC1}
      - RTSP_OUTPUT=${RTSP_OUTPUT}
      - RTSP_SERVER=${RTSP_SERVER}
      - RTSP_PATH=${RTSP_PATH}
      - RENDER_MODE=${RENDER_MODE}
    volumes:
      - ./results:/tmp/results
      - ~/.Xauthority:/home/dlstreamer/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/dri:/dev/dri
      - ~/.cl-cache:/home/pipeline-server/.cl-cache
      - ./models:/home/pipeline-server/models
      - ./src:/home/pipeline-server/src
      - ./src/extensions:/home/pipeline-server/extensions
    restart: on-failure
