version: '3.7'
services:
  camera-simulator:
    container_name: camera-simulator
    image: aler9/rtsp-simple-server
    ports:
      - "127.0.0.1:8554:8554"
  camera-simulator0:
    build:
      context: .
    image: openvino/ubuntu20_data_runtime:2021.4.2
    container_name: camera-simulator0
    network_mode: "host"
    entrypoint: ffmpeg
    command: "
        -nostdin
        -re -stream_loop -1
        -i /home/pipeline-server/sample-media/coca-cola-4465029-3840-15-bench.mp4
        -c copy
        -f rtsp
        -rtsp_transport
        tcp
        rtsp://localhost:8554/camera_0
        "
    depends_on:
      - camera-simulator
    volumes:
      - ./sample-media:/home/pipeline-server/sample-media
  camera-simulator1:
    build:
      context: .
    image: openvino/ubuntu20_data_runtime:2021.4.2
    container_name: camera-simulator1
    network_mode: "host"
    entrypoint: ffmpeg
    command: "
        -nostdin
        -re -stream_loop -1
        -i /home/pipeline-server/sample-media/couple-paying-at-the-counter-in-the-grocery-4121754-3840-15-bench.mp4
        -c copy
        -f rtsp
        -rtsp_transport
        tcp
        rtsp://localhost:8554/camera_1
        "
    depends_on:
      - camera-simulator
    volumes:
      - ./sample-media:/home/pipeline-server/sample-media
  camera-simulator2:
    build:
      context: .
    image: openvino/ubuntu20_data_runtime:2021.4.2
    container_name: camera-simulator2
    network_mode: "host"
    entrypoint: ffmpeg
    command: "
        -nostdin
        -re -stream_loop -1
        -i /home/pipeline-server/sample-media/vehicle-bike-3840-15-bench.mp4
        -c copy
        -f rtsp
        -rtsp_transport
        tcp
        rtsp://localhost:8554/camera_2
        "
    depends_on:
      - camera-simulator
    volumes:
      - ./sample-media:/home/pipeline-server/sample-media