#
# Copyright (C) 2023 Intel Corporation.
#
# SPDX-License-Identifier: Apache-2.0
#

# base image
FROM python:alpine3.18

RUN mkdir -p /app /configFiles
COPY update_server_device.py /app

WORKDIR /app
ENTRYPOINT [ "python3", "update_server_device.py"]