apiVersion: v1
kind: Service
metadata:
  name: camera-simulator
  labels:
    app: camera-simulator
spec:
  ports:
    - port: {{ .Values.cameraSimulator.port }}
      targetPort: {{ .Values.cameraSimulator.port }}
  selector:
    app: camera-simulator