apiVersion: apps/v1
kind: Deployment
metadata:
  name: camera-simulator
  labels:
    app: camera-simulator
spec:
  replicas: {{ .Values.cameraSimulator.replicas }}
  selector:
    matchLabels:
      app: camera-simulator
  template:
    metadata:
      labels:
        app: camera-simulator
    spec:
      containers:
        - image: {{ .Values.cameraSimulator.image }}
          name: camera-simulator
          env:
            - name: HTTP_PROXY
              value: "{{ .Values.global.env.HTTP_PROXY }}"
            - name: HTTPS_PROXY
              value: "{{ .Values.global.env.HTTPS_PROXY }}"
            - name: NO_PROXY
              value: "{{ .Values.global.env.NO_PROXY }}"
          ports:
            - containerPort: {{ .Values.cameraSimulator.port }}
              protocol: TCP
      restartPolicy: Always