apiVersion: v1
kind: ConfigMap
metadata:
  name: dlstreamer-config
  labels:
    app: dlstreamer
data:
  yolov5-cpu.env: |
    COLOR_WIDTH=1920
    COLOR_HEIGHT=1080
    COLOR_FRAMERATE=15
    OCR_SPECIFIED=5
    GST_DEBUG=0
    GST_PIPELINE_LAUNCH=/home/pipeline-server/pipelines/yolo11n.sh
    OCR_DEVICE=
    LOG_LEVEL=ERROR
    CPU_SW_DECODER=force-sw-decoders=1
    DECODE=decodebin force-sw-decoders=1
    DEVICE=CPU
    DETECTION_OPTIONS=gpu-throughput-streams=4 nireq=4 batch-size=1
    CLASSIFICATION_OPTIONS=reclassify-interval=1 $DETECTION_OPTIONS
    OCR_RECLASSIFY_INTERVAL=5
    BARCODE_RECLASSIFY_INTERVAL=5
    RENDER_MODE=1

  yolo11n.sh: |
    # Simplified pipeline script
    gst-launch-1.0 filesrc location=/mnt/rtsp-media/obj_classification-1920-15-bench.mp4 ! decodebin ! videoconvert ! gvadetect model=/mnt/models/object_detection/yolo11n/FP16-INT8/yolo11n.xml model-proc=/mnt/models/object_detection/yolo11n/yolo11n.json labels=/mnt/models/object_detection/yolo11n/imagenet_2012.txt ! gvametaconvert ! gvawatermark ! videoconvert ! fpsdisplaysink video-sink=ximagesink sync=true --verbose

  yolo11n_full.sh: |
    # Full pipeline script
    gst-launch-1.0 filesrc location=/mnt/rtsp-media/obj_classification-1920-15-bench.mp4 ! decodebin ! videoconvert ! gvadetect model=/mnt/models/object_detection/yolo11n/FP16-INT8/yolo11n.xml model-proc=/mnt/models/object_detection/yolo11n/yolo11n.json labels=/mnt/models/object_detection/yolo11n/imagenet_2012.txt ! gvatrack name=tracking tracking-type=zero-term-imageless ! gvaclassify model-instance-id=classifier labels=/mnt/models/object_classification/efficientnet-b0/imagenet_2012.txt model=/mnt/models/object_classification/efficientnet-b0/FP32/efficientnet-b0.xml model-proc=/mnt/models/object_classification/efficientnet-b0/efficientnet-b0.json reclassify-interval=1 device=CPU inference-region=roi-list name=classification ! gvapython class=ObjectFilter module=/mnt/extensions/tracked_object_filter.py kwarg="{\"reclassify_interval\": 5}" name=tracked_object_filter ! gvametaconvert ! gvametapublish name=destination file-format=json-lines file-path=/tmp/results/r\$cid.jsonl ! gvawatermark ! videoconvert ! fpsdisplaysink video-sink=ximagesink sync=true --verbose

  yolo11n_effnetv2b0.sh: |
    # EfficientNet pipeline script (default)
    gst-launch-1.0 filesrc location=/mnt/rtsp-media/obj_classification-1920-15-bench.mp4 ! decodebin ! videoconvert ! gvadetect model=/mnt/models/object_detection/yolo11n/FP16-INT8/yolo11n.xml model-proc=/mnt/models/object_detection/yolo11n/yolo11n.json labels=/mnt/models/object_detection/yolo11n/imagenet_2012.txt ! gvatrack name=tracking tracking-type=zero-term-imageless ! gvaclassify model-instance-id=classifier labels=/mnt/models/object_classification/efficientnet-v2-b0/INT8/imagenet_2012.txt model=/mnt/models/object_classification/efficientnet-v2-b0/INT8/efficientnet-v2-b0-int8.xml model-proc=/mnt/models/object_classification/efficientnet-v2-b0/INT8/preproc-aspect-ratio.json device=CPU inference-region=roi-list name=classification ! gvametaconvert ! gvawatermark ! videoconvert ! fpsdisplaysink video-sink=ximagesink sync=true --verbose