apiVersion: v1
kind: Service
metadata:
  name: mqtt-broker
  labels:
    app: mqtt-broker
spec:
  ports:
    - port: {{ .Values.mqttBroker.port }}
      targetPort: {{ .Values.mqttBroker.port }}
  selector:
    app: mqtt-broker