#
# Copyright (C) 2023 Intel Corporation.
#
# SPDX-License-Identifier: Apache-2.0
#

FROM golang:1.20.9-alpine3.18 AS builder
RUN apk update && \
    apk add make autoconf libtool protobuf-dev && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /test

# install docker, as we need docker for some unit tests
RUN apk update && apk add --update docker openrc && \
    rm -rf /var/lib/apt/lists/*

COPY . .

RUN chmod +x /test/run_unit_test.sh

ENTRYPOINT ["/test/run_unit_test.sh"]
