apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -o kubernetes -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: camera-simulator
  name: camera-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: camera-simulator
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert -o kubernetes -c
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: camera-simulator
    spec:
      containers:
        - image: aler9/rtsp-simple-server
          name: camera-simulator
          ports:
            - containerPort: 8554
          resources: {}
      restartPolicy: Always
status: {}
