OvmsSingleContainer: false
OvmsServer:
  ServerDockerScript: start_ovms_server.sh
  ServerDockerImage: openvino/model_server:2023.1-gpu
  ServerContainerName: ovms-server
  ServerConfig: "/models/config.json"
  StartupMessage: Starting OVMS server
  InitWaitTime: 10s
  EnvironmentVariableFiles:
    - ovms_server.env
  # StartUpPolicy:
  # when there is an error on launching ovms server startup, choose one of these values for the behavior of profile-launcher: 
  #   remove-and-restart: it will remove the existing container with the same container name if any and then restart the container
  #   exit: it will exit the profile-launcher and 
  #   ignore: it will ignore the error and continue (this is the default value if not given or none of the above)
  StartUpPolicy: ignore    
OvmsClient:
  DockerLauncher:
    Script: docker-launcher.sh
    DockerImage: grpc_python:dev
    ContainerName: grpc_python
    Volumes:
      - "$RUN_PATH/results:/tmp/results"
  PipelineScript: /app/run_grpc_python.sh
  PipelineInputArgs: "--model_name instance-segmentation-security-1040" # space delimited like we run the script in command and take those input arguments
  # PipelineInputArgs: "--model_name bit_64" # space delimited like we run the script in command and take those input arguments
  # PipelineInputArgs: "--model_name yolov5s" # space delimited like we run the script in command and take those input arguments
  EnvironmentVariableFiles:
    - grpc_python.env