#!/bin/bash
#
# Copyright (C) 2024 Intel Corporation.
#
# SPDX-License-Identifier: Apache-2.0
#

cl_cache_dir="/home/pipeline-server/.cl-cache" \
DISPLAY="$DISPLAY" \
RESULT_DIR="/tmp/result" \
DECODE="$DECODE" \
DEVICE="$DEVICE" \
PRE_PROCESS="$PRE_PROCESS" \
AGGREGATE="$AGGREGATE" \
OUTPUTFORMAT="$OUTPUTFORMAT" \
BARCODE_RECLASSIFY_INTERVAL="$BARCODE_INTERVAL" \
OCR_RECLASSIFY_INTERVAL="$OCR_INTERVAL" \
OCR_DEVICE="$OCR_DEVICE" \
LOG_LEVEL="$LOG_LEVEL" \
GST_DEBUG="$GST_DEBUG" \
LOW_POWER="$LOW_POWER" \
cid_count="$cid_count" \
inputsrc="$inputsrc" \
RUN_MODE="$RUN_MODE" \
CPU_ONLY="$CPU_ONLY" \
OCR_RECLASSIFY_INTERVAL="$OCR_RECLASSIFY_INTERVAL" \
BARCODE_RECLASSIFY_INTERVAL="$BARCODE_RECLASSIFY_INTERVAL" \
AUTO_SCALE_FLEX_140="$AUTO_SCALE_FLEX_140" \
PIPELINE_SCRIPT="$PIPELINE_SCRPT" \
/opencv-ovms/scripts/run_gst.sh --pipeline_script_choice "$PIPELINE_SCRIPT"
