# https://github.com/dlstreamer/pipeline-zoo-models/tree/main/storage/efficientnet-b0_INT8
- model: efficientnet-b0
# https://storage.openvinotoolkit.org/repositories/open_model_zoo/2022.1/models_bin/3/horizontal-text-detection-0001/
- model: horizontal-text-detection-0001
# https://github.com/dlstreamer/pipeline-zoo-models/tree/main/storage/text-recognition-0012-mod
- model: text-recognition-0012-mod
# https://storage.openvinotoolkit.org/repositories/open_model_zoo/2022.1/models_bin/3/text-recognition-0014/
- model: text-recognition-0014
# https://github.com/dlstreamer/pipeline-zoo-models/tree/main/storage/yolov5s-416
- model: yolov5s
# https://github.com/dlstreamer/pipeline-zoo-models/tree/main/storage/yolov5s-416_INT8
- model: yolov5s-INT8