#!/bin/bash
#
# Copyright (C) 2023 Intel Corporation.
#
# SPDX-License-Identifier: Apache-2.0
#

if [ "$INPUTSRC_TYPE" == "REALSENSE" ]; then
	decode_pp="! videoconvert ! video/x-raw,format=BGR"
fi

if [ "$RENDER_MODE" == "1" ]; then
	gst-launch-1.0 $inputsrc ! decodebin force-sw-decoders=true $decode_pp ! gvadetect model-instance-id=odmodel name=detection model=models/yolov5s/1/FP32-INT8/yolov5s.xml model-proc=models/yolov5s/1/yolov5s.json threshold=.5 device=CPU ! gvatrack name=tracking tracking-type=zero-term-imageless ! tee name=branch ! queue ! gvaclassify model-instance-id=clasifier labels=models/efficientnet-b0/1/imagenet_2012.txt model=models/efficientnet-b0/1/FP16-INT8/efficientnet-b0.xml model-proc=models/efficientnet-b0/1/efficientnet-b0.json reclassify-interval=1 device=CPU inference-region=roi-list name=classification ! gvametaaggregate name=aggregate ! gvametaconvert name=metaconvert add-empty-results=true ! gvametapublish name=destination file-format=2 file-path=/tmp/results/r$cid_count.jsonl branch. \
	! queue ! gvapython class=ObjectFilter module=/home/pipeline-server/extensions/tracked_object_filter.py name=tracked_object_filter ! gvadetect model-instance-id=ocr threshold=.40 model=models/horizontal-text-detection-0001/1/FP16-INT8/horizontal-text-detection-0001.xml model-proc=models/horizontal-text-detection-0001/1/horizontal-text-detection-0001.json name=text_detection device=CPU inference-region=roi-list ! gvainference model-instance-id=ocr2 model=models/text-recognition-0014/1/FP16-INT8/text-recognition-0014.xml model-proc=models/text-recognition-0014/1/text-recognition-0012.json inference-region=roi-list name=text_recognition object-class=text ! gvapython class=OCR module=/home/pipeline-server/extensions/OCR_post_processing.py name=ocr_postprocess ! aggregate. branch. ! queue ! videoconvert ! video/x-raw,format=BGR ! gvapython name=barcode class=BarcodeDetection module=/home/pipeline-server/extensions/barcode.py ! aggregate. branch. ! queue \
	! gvawatermark \
        ! videoconvert ! fpsdisplaysink video-sink=ximagesink sync=true --verbose
        2>&1 | tee >/tmp/results/gst-launch_xeon_$cid_count.log >(stdbuf -oL sed -n -e 's/^.*current: //p' | stdbuf -oL cut -d , -f 1 > /tmp/results/pipeline$cid_count.log)
else
	gst-launch-1.0 $inputsrc ! decodebin force-sw-decoders=true $decode_pp ! gvadetect model-instance-id=odmodel name=detection model=models/yolov5s/1/FP32-INT8/yolov5s.xml model-proc=models/yolov5s/1/yolov5s.json threshold=.5 device=CPU ! gvatrack name=tracking tracking-type=zero-term-imageless ! tee name=branch ! queue ! gvaclassify model-instance-id=clasifier labels=models/efficientnet-b0/1/imagenet_2012.txt model=models/efficientnet-b0/1/FP16-INT8/efficientnet-b0.xml model-proc=models/efficientnet-b0/1/efficientnet-b0.json reclassify-interval=1 device=CPU inference-region=roi-list name=classification ! gvametaaggregate name=aggregate ! gvametaconvert name=metaconvert add-empty-results=true ! gvametapublish name=destination file-format=2 file-path=/tmp/results/r$cid_count.jsonl ! fpsdisplaysink video-sink=fakesink sync=true --verbose branch. ! queue ! gvapython class=ObjectFilter module=/home/pipeline-server/extensions/tracked_object_filter.py name=tracked_object_filter ! gvadetect model-instance-id=ocr threshold=.40 model=models/horizontal-text-detection-0001/1/FP16-INT8/horizontal-text-detection-0001.xml model-proc=models/horizontal-text-detection-0001/1/horizontal-text-detection-0001.json name=text_detection device=CPU inference-region=roi-list ! gvainference model-instance-id=ocr2 model=models/text-recognition-0014/1/FP16-INT8/text-recognition-0014.xml model-proc=models/text-recognition-0014/1/text-recognition-0012.json inference-region=roi-list name=text_recognition object-class=text ! gvapython class=OCR module=/home/pipeline-server/extensions/OCR_post_processing.py name=ocr_postprocess ! aggregate. branch. ! queue ! videoconvert ! video/x-raw,format=BGR ! gvapython name=barcode class=BarcodeDetection module=/home/pipeline-server/extensions/barcode.py ! aggregate. 2>&1 | tee >/tmp/results/gst-launch_xeon_$cid_count.log >(stdbuf -oL sed -n -e 's/^.*current: //p' | stdbuf -oL cut -d , -f 1 > /tmp/results/pipeline$cid_count.log)
fi
