#
# Copyright (C) 2024 Intel Corporation.
#
# SPDX-License-Identifier: Apache-2.0
#

FROM openvino/ubuntu20_data_runtime:2021.4.2

USER root
RUN apt-get update && apt-get install --no-install-recommends -y wget

RUN mkdir -p /sample-media && wget -O /sample-media/00-coca-cola-4465029-1920-15-bench.mp4 https://www.pexels.com/download/video/4465029/