OvmsSingleContainer: true
OvmsClient:
  DockerLauncher:
    Script: docker-launcher.sh
    DockerImage: openvino/model_server-capi-gst-ovms-capi_yolov5:latest
    ContainerName: capi_yolov5
    Volumes:
      - "$cl_cache_dir:/home/intel/gst-ovms/.cl-cache"
      - /tmp/.X11-unix:/tmp/.X11-unix
      - "$RUN_PATH/sample-media/:/home/intel/gst-ovms/vids"
      - "$RUN_PATH/configs/opencv-ovms/gst_capi/extensions:/home/intel/gst-ovms/extensions"
      - "$RUN_PATH/results:/tmp/results"
      - "$RUN_PATH/configs/opencv-ovms/models/2022/:/models"
  PipelineScript: ./run_gst_capi.sh
  PipelineInputArgs: "" # space delimited like we run the script in command and take those input arguments
  EnvironmentVariableFiles:
    - capi_yolov5.env
