# Copyright © 2023 Intel Corporation. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

.PHONY: build

#	mkdir -p build
# docker build --output=bin --tag grpc:dev .
build:
	docker build --tag grpc:dev .