name: Bandit
on: [pull_request]
jobs:
  bandit:
    name: runner / bandit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install bandit
        run: |
          pip install bandit && bandit --version
      - name: Run bandit
        run: |
          bandit -r ./ -f custom --msg-template "{relpath}:{line}:{col}:{test_id}:{severity}:{msg}"
      