name: Build docker images

on: workflow_dispatch

permissions:
  contents: read

jobs:
  build_SOC:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Make soc Docker images
            run: |
              make build-soc
  build_DGPU:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Make dgpu Docker images
            run: |
              make build-dgpu
  build_OVMS_Profile_Launcher:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Build ovms profile launcher
            run: |
              make build-profile-launcher
