name: Build docker images

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout code
            uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
          - name: Make dlstreamer Docker image
            run: |
              make build
