name: "Discord-Issues"

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs:
  run_integration_tests:
      runs-on: [self-hosted, linux, x64, integration, arc, 12gen]
      steps:
          - name: Cleanup repo build folder
            run: |
              ls -la ./
              sudo rm -rf ./* || true
              sudo rm -rf ./.??* || true
              ls -la ./
          - name: Checkout code
            uses: actions/checkout@v3 
          - name: run integration tests
            run: |
              make build-dlstreamer
          - name: success
            env:
              DISCORD_INTEGRATION: ${{ secrets.DISCORD_INTEGRATION }}
              TEST_ENV: ${{ secrets.TEST }}
            run: |
              echo $DISCORD_INTEGRATION
              echo $TEST_ENV
              curl --location --request POST ${{ secrets.DISCORD_INTEGRATION }} --header 'Content-Type: application/json' --data-raw '{"content": "sucess"}'
