on: [push, pull_request]
name: Golang test
permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.20.x]
        os: [ubuntu-latest] # macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@v5.1.0
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v4
#     - run: go test ./... 
