name: PyCodestyle
on: [pull_request]
jobs:
  bandit:
    name: runner / PyCodestyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pycodestyle
        run: |
          pip install pycodestyle
          pip install --upgrade pycodestyle
      - name: Run pycodestyle
        run: |
          pycodestyle --show-source --show-pep8 .