name: trivy code scan
on:
  push:
    branches:
    - master
  pull_request:
jobs:
  trivy_scan:
    name: trivy scan
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        trivy-config: ./github/.trivyConf.yaml